Feature/exercicio1
HebertFSoares/Orion-Bootcamp pull request #1
Opened 2023-10-10 20:00 UTC by HebertFSoares

2023-10-10 20:03 UTC, HebertFSoares commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Hebert Soares] Exercício 1](https://trello.com/c/KVXNUXwF/103-hebert-soares-exerc%C3%ADcio-1)

2023-10-11 01:49 UTC, dairsposito requested changes
Quando insiro uma palavra com acentos, não está retornando corretamente.

2023-10-11 01:49 UTC, dairsposito commented on src/ex01.ts
> +function contadorVogais(palavra: string): number {
É importante sempre documentar as funções.

2023-10-11 01:49 UTC, dairsposito commented on src/ex01.ts
> +    const todasVogais: string[] = ['a', 'e', 'i', 'o', 'u'];
Interessante considerar também vogais com acentos.

2023-10-11 01:49 UTC, dairsposito commented on src/ex01.ts
> +      if (todasVogais.indexOf(palavra[i]) !== -1) {
Legal a maneira como você fez. Acredita que o método includes fica mais legível?

2023-10-11 19:18 UTC, HebertFSoares commented on src/ex01.ts
> +      if (todasVogais.indexOf(palavra[i]) !== -1) {
identifiquei um problema no uso do método includes. O TypeScript apontou o erro no código porque o método includes não é nativo de um array de strings.

2023-10-12 02:07 UTC, dairsposito requested changes

2023-10-12 02:07 UTC, dairsposito commented on src/ex01.ts
> +function contadorWeb() {
Documentar a função e fazer a tipagem do parâmetro e retorno da função.

2023-10-12 02:07 UTC, dairsposito commented on src/ex01.ts
> +    const todasVogais: string[] = ['a', 'e', 'i', 'o', 'u', 'á', 'é', 'í', 'ó', 'ú', 'à', 'è', 'ì', 'ò', 'ù'];
![image](https://github.com/HebertFSoares/Orion-Bootcamp/assets/37427121/ed85f556-476d-417d-b84f-190748c6c539)
Por algum motivo não está sendo possível contar vogais com acento.

2023-10-12 02:53 UTC, merged