Feature/exercicio2
HebertFSoares/Orion-Bootcamp pull request #2
Opened 2023-10-13 20:33 UTC by HebertFSoares

2023-10-13 20:39 UTC, HebertFSoares commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Hebert Soares] Exercício 2](https://trello.com/c/hSogtyr9/116-hebert-soares-exerc%C3%ADcio-2)

2023-10-13 22:08 UTC, dairsposito requested changes

2023-10-13 22:08 UTC, dairsposito commented on src/ex02.ts
> +function obterBiografiaPorID(id: number, listaPessoas: Pessoa[]): string {
Documentar todas as funções

2023-10-13 22:08 UTC, dairsposito commented on dist/index02.html
A página web será apenas no exercício 3

2023-10-13 22:08 UTC, dairsposito commented on src/ex02.ts
Para todas as funções ficaram faltando 1 paradigma.
Funções no paradigma funcional: obterBiografiaPorID e obterNomePorID
Funções no paradigma imperativo: removerPessoaPorID e alterarRegistroPorID

Para todas as funções, demonstrar ambos os paradigmas. Logo, se são 4 funções para 2 paradigmas cada, deverão existir 8 funções. 4 no funcional e 4 no imperativo.

2023-10-13 22:08 UTC, dairsposito commented on src/ex02.ts
> +function exibirRegistros(lista: Pessoa[]) {
Da mesma forma, esse código seria competente ao exercício 3.

2023-10-13 23:54 UTC, dairsposito requested changes

2023-10-13 23:54 UTC, dairsposito commented on src/ex02.ts
Ficou faltando documentar as funções.

2023-10-13 23:54 UTC, dairsposito commented on src/ex02.ts
> +function obterBiografiaPorIDImperativo(id: number, listaPessoas: Pessoa[]): string {
No paradigma imperativo, não há a necessidade de informar a lista no parâmetro da função.

2023-10-13 23:54 UTC, dairsposito commented on dist/js/ex02.js
Remover os arquivos compilados do versionamento.

2023-10-14 00:31 UTC, dairsposito reviewed
Ficou bom. Para o exercício 3, considerar remover a passagem da lista para as funções de paradigma imperativo. Como não é obrigatório, vou mergear.

2023-10-14 00:31 UTC, dairsposito commented on src/ex02.ts
> +function obterNomePorIDImperativo(id: number, listaPessoas: Pessoa[]): string {
No imperativo não há a necessidade de informar a lista, a função pode alterar/acessar a lista original.

2023-10-14 00:31 UTC, dairsposito commented on src/ex02.ts
> +function removerPessoaPorIDImperativo(id: number, listaPessoas: Pessoa[]): string {
No imperativo não há a necessidade de informar a lista, a função pode alterar/acessar a lista original.

2023-10-14 00:31 UTC, dairsposito commented on src/ex02.ts
> +function alterarRegistroPorIDImperativo(id: number, campo: string, novoTexto: string, listaPessoas: Pessoa[]): string {
No imperativo não há a necessidade de informar a lista, a função pode alterar/acessar a lista original.

2023-10-14 05:07 UTC, merged